<?php

namespace GoldenLine\WorkshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicBenefitOrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicBenefitOrganizationRepository extends EntityRepository
{
}
